/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package semana6;

import java.util.Scanner;
import java.util.Random;

/**
 *
 * @author andre
 */
public class Martinez_Andrea_Arreglos extends javax.swing.JFrame {

    /**
     * Creates new form Martinez_Andrea_Arreglos
     */
    public Martinez_Andrea_Arreglos() {
        initComponents();

        AHORCADO.setVisible(false);
        CAMBIARPALABRA.setVisible(false);
        jLabel11.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MENU = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ahorcado = new javax.swing.JButton();
        cambiarpalabra = new javax.swing.JButton();
        AHORCADO = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        letra = new javax.swing.JTextField();
        volver1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        oculta = new javax.swing.JLabel();
        palabrarandomoculta = new javax.swing.JLabel();
        denuevo = new javax.swing.JLabel();
        numintentos = new javax.swing.JLabel();
        CAMBIARPALABRA = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        volver2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(572, 363));

        MENU.setPreferredSize(new java.awt.Dimension(572, 363));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 36)); // NOI18N
        label1.setText("MENU");

        jLabel1.setText("--------------------------------------------------------------------------------------");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Juego de Ahorcado");

        ahorcado.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        ahorcado.setForeground(new java.awt.Color(204, 0, 51));
        ahorcado.setText("JUGAR");
        ahorcado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ahorcadoActionPerformed(evt);
            }
        });

        cambiarpalabra.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cambiarpalabra.setForeground(new java.awt.Color(204, 0, 51));
        cambiarpalabra.setText("CAMBIAR PALABRAS");
        cambiarpalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarpalabraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MENULayout = new javax.swing.GroupLayout(MENU);
        MENU.setLayout(MENULayout);
        MENULayout.setHorizontalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENULayout.createSequentialGroup()
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MENULayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel5))
                    .addGroup(MENULayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(ahorcado))
                    .addGroup(MENULayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(cambiarpalabra))
                    .addGroup(MENULayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MENULayout.createSequentialGroup()
                .addGap(0, 88, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(71, 71, 71))
        );
        MENULayout.setVerticalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENULayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ahorcado)
                .addGap(18, 18, 18)
                .addComponent(cambiarpalabra)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        AHORCADO.setPreferredSize(new java.awt.Dimension(572, 363));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setText("AHORCADO");

        jLabel3.setText("-------------------------------------------------------------");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese una letra:");

        letra.setToolTipText("");
        letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraActionPerformed(evt);
            }
        });

        volver1.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Documents\\flecha-correcta.png")); // NOI18N
        volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Oportunidad:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        oculta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oculta.setText("jLabel12");

        palabrarandomoculta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        palabrarandomoculta.setText("jLabel12");

        numintentos.setText("jLabel10");

        javax.swing.GroupLayout AHORCADOLayout = new javax.swing.GroupLayout(AHORCADO);
        AHORCADO.setLayout(AHORCADOLayout);
        AHORCADOLayout.setHorizontalGroup(
            AHORCADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AHORCADOLayout.createSequentialGroup()
                .addGroup(AHORCADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AHORCADOLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(volver1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(AHORCADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AHORCADOLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AHORCADOLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel2))
                            .addGroup(AHORCADOLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(AHORCADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AHORCADOLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(letra, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(AHORCADOLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(numintentos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(denuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(AHORCADOLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(AHORCADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palabrarandomoculta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oculta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        AHORCADOLayout.setVerticalGroup(
            AHORCADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AHORCADOLayout.createSequentialGroup()
                .addGroup(AHORCADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AHORCADOLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(volver1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AHORCADOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AHORCADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AHORCADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(numintentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denuevo)
                .addGap(28, 28, 28)
                .addComponent(oculta)
                .addGap(18, 18, 18)
                .addComponent(palabrarandomoculta)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        CAMBIARPALABRA.setPreferredSize(new java.awt.Dimension(572, 363));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("CAMBIAR PALABRA");

        jLabel8.setText("----------------------------------------------------------------");

        volver2.setIcon(new javax.swing.ImageIcon("C:\\Users\\andre\\Documents\\flecha-correcta.png")); // NOI18N
        volver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout CAMBIARPALABRALayout = new javax.swing.GroupLayout(CAMBIARPALABRA);
        CAMBIARPALABRA.setLayout(CAMBIARPALABRALayout);
        CAMBIARPALABRALayout.setHorizontalGroup(
            CAMBIARPALABRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAMBIARPALABRALayout.createSequentialGroup()
                .addGroup(CAMBIARPALABRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CAMBIARPALABRALayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(volver2)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CAMBIARPALABRALayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel8))
                    .addGroup(CAMBIARPALABRALayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        CAMBIARPALABRALayout.setVerticalGroup(
            CAMBIARPALABRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAMBIARPALABRALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CAMBIARPALABRALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(volver2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AHORCADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MENU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CAMBIARPALABRA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AHORCADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MENU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CAMBIARPALABRA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String[] palabra = {"HONDURAS", "AMOR", "BALON", "SECADORA", "CUADERNO", "FLOR", "COMPUTADORA", "CANASTA", "TELEFONO", "ENTRENADOR"};
    Scanner texto = new Scanner(System.in);
    Random random = new Random();
    String palabraoculta = "";
    String palabraactual = "";
    int contador = 5;

    private void cambiarpalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarpalabraActionPerformed
        CAMBIARPALABRA.setVisible(true);
        MENU.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarpalabraActionPerformed

    private void ahorcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ahorcadoActionPerformed
        MENU.setVisible(false);
        CAMBIARPALABRA.setVisible(false);
oculta.setVisible(false);
        AHORCADO.setVisible(true);
        int aleatorio = random.nextInt(1, 11);

        palabraactual = palabra[aleatorio];
        palabraoculta = "";

        for (int i = 0; i < palabraactual.length(); i++) {
            palabraoculta += ("_" + " ");
        }
        oculta.setText(palabraactual);
        palabrarandomoculta.setText(palabraoculta);
        numintentos.setText("" + contador);

        // TODO add your handling code here:
    }//GEN-LAST:event_ahorcadoActionPerformed

    private void letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letraActionPerformed

    private void volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver1ActionPerformed
        AHORCADO.setVisible(false);
        MENU.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_volver1ActionPerformed

    private void volver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver2ActionPerformed
        CAMBIARPALABRA.setVisible(false);
        MENU.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_volver2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String letraintento = letra.getText().toUpperCase();
        if (letraintento.length() != 1) {
            jLabel11.setText("Solo puede ingresar un caracter");
            return;

        }  

            String palabraocultaactual = oculta.getText();
            String[] palabrarandom = palabrarandomoculta.split(" ");

            for (int i = 0; i < palabraactual.length(); i++) {
                if (String.valueOf(palabraactual.charAt(i)).equals(letraintento)) {
                    palabrarandom[i] = letraintento;
                    numintentos.setText("" + contador);
                    denuevo.setVisible(false);
                    denuevo.setText("Le pegaste a una letra!");

                }else{
                    contador--;
                    numintentos.setText("" + contador);
                    denuevo.setText("Maal, intente de nuevo");

                }
                

            

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Martinez_Andrea_Arreglos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Martinez_Andrea_Arreglos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Martinez_Andrea_Arreglos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Martinez_Andrea_Arreglos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Martinez_Andrea_Arreglos().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AHORCADO;
    private javax.swing.JPanel CAMBIARPALABRA;
    private javax.swing.JPanel MENU;
    private javax.swing.JButton ahorcado;
    private javax.swing.JButton cambiarpalabra;
    private javax.swing.JLabel denuevo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label label1;
    private javax.swing.JTextField letra;
    private javax.swing.JLabel numintentos;
    private javax.swing.JLabel oculta;
    private javax.swing.JLabel palabrarandomoculta;
    private javax.swing.JButton volver1;
    private javax.swing.JButton volver2;
    // End of variables declaration//GEN-END:variables
}
